tools:
  exceptions: https://sentry.io/organizations/jerryrat/issues/?project=6036387
  ci: ../github/workflows/CI-test.yml

services:
  production: https://herokujerryratapp.herokuapp.com/

docs:
  getting_started: ./README.md
  
commands:
  bootstrap: script/bootstrap
  database: TBD
  server: cd app; python3 manage.py runserver
