# Generated by Django 3.2.8 on 2021-12-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barchart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xaxis', models.CharField(choices=[('age', 'age'), ('job', 'job'), ('marital', 'marital'), ('education', 'education'), ('default', 'default'), ('housing', 'housing'), ('loan', 'loan')], default='age', max_length=32)),
                ('yaxis', models.CharField(choices=[('month', 'month'), ('day_of_week', 'day_of_week'), ('campaign', 'campaign'), ('pdays', 'pdays'), ('previous', 'previous'), ('poutcome', 'poutcome')], default='month', max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DoubleBarChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xaxis', models.CharField(choices=[('age', 'age'), ('job', 'job'), ('marital', 'marital'), ('education', 'education'), ('default', 'default'), ('housing', 'housing'), ('loan', 'loan')], default='age', max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='linechart',
            name='xaxis',
            field=models.CharField(choices=[('age', 'age'), ('job', 'job'), ('marital', 'marital'), ('education', 'education'), ('default', 'default'), ('housing', 'housing'), ('loan', 'loan')], default='age', max_length=32),
        ),
        migrations.AlterField(
            model_name='linechart',
            name='yaxis',
            field=models.CharField(choices=[('month', 'month'), ('day_of_week', 'day_of_week'), ('campaign', 'campaign'), ('pdays', 'pdays'), ('previous', 'previous'), ('poutcome', 'poutcome')], default='month', max_length=32),
        ),
    ]
