# Generated by Django 3.2.8 on 2021-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('dataid', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=255)),
                ('marital', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('default', models.CharField(max_length=10)),
                ('housing', models.CharField(max_length=10)),
                ('loan', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=5)),
                ('day_of_week', models.CharField(max_length=5)),
                ('duration', models.IntegerField()),
                ('campaign', models.IntegerField()),
                ('pdays', models.IntegerField()),
                ('previous', models.IntegerField()),
                ('poutcome', models.CharField(max_length=255)),
                ('emp_var_rate', models.DecimalField(db_column='emp.var.rate', decimal_places=1, max_digits=4)),
                ('cons_price_idx', models.DecimalField(db_column='cons.price.idx', decimal_places=3, max_digits=5)),
                ('cons_conf_idx', models.DecimalField(db_column='cons.conf.idx', decimal_places=1, max_digits=3)),
                ('euribor3m', models.DecimalField(decimal_places=3, max_digits=4)),
                ('nr_employed', models.DecimalField(db_column='nr.employed', decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'userdata',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
