# Generated by Django 3.2.8 on 2021-10-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial_data'),
        ('myapp', '0002_user'),
    ]

    operations = [
    ]
