# Generated by Django 3.2.8 on 2021-11-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211030_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linechart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('xaxis', models.CharField(max_length=32)),
                ('yaxis', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
