name: Django CI

env:
  DB_HOST: localhost
  DB_DATABASE: jerryratdb
  DB_USER: dbadmin
  DB_PASSWORD: 12345
  MYSQL_ROOT_PASSWORD: root

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u root -p${{ env.MYSQL_ROOT_PASSWORD }}
        mysql -e 'CREATE USER IF NOT EXISTS ${{ env.DB_USER }} IDENTIFIED BY '${{ env.DB_PASSWORD }}';'
        mysql -e "GRANT ALL ON ${{ env.DB_DATABASE }}.* TO '${{ env.DB_USER }}'@'%' WITH GRANT OPTION;"
        mysql -e 'FLUSH PRIVILEGES'
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
    - name: Migrations
      run: |
        cd app
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        cd app
        python manage.py test
