name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Sentry CLI
      uses: mathieu-bour/setup-sentry-cli@1.2.0
      with:
        version: latest # optional if 'latest'
        url: https://sentry.io # optional if you are using https://sentry.io
        token: ${{ SECRETS.SENTRY_TOKEN }} # from GitHub secrets
        organization: university_of_toronto
        project: jerryrat
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
    - name: Setup MySQL
        run: |
          mysql -u root -p < app/myapp/sql/createDataBase.sql
          mysql -u root -p < app/myapp/sql/initDataBase.sql
    - name: Run Tests
      run: |
        python app/manage.py test
